### Site info:
title: Medicare Blog
tagline: The Official Blog for U.S. Medicare Program. For more information, please visit www.medicare.gov

author: Mohanraj Balasubramanian

baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "medicare-blog.github.io" # the base hostname & protocol for your site

### Personal info and site tools info:

favicon:     "/images/favicon.ico

lsi: false

parmalink: /:categories/:title.html

### Build settings
markdown: rdiscount
highlighter: pygments
paginate: 5

exclude:
    - LICENSE
    - README.md

prose:
    siteurl: 'https://ndarville.github.io'
    metadata:
        _drafts:
            - name: layout
              field:
                  element: hidden
                  value: post
            - name: categories
              field:
                  element: hidden
                  value: blog
            - name: title
              field:
                  element: text
                  value: ""
            - name: date
              field:
                  element: hidden
                  value: ""
            - name: excerpt
              field:
                  element: text
                  value: ""
                  placeholder: Use 200 characters at most.
            - name: id
              field:
                  element: hidden
                  value: ""
            - name: tags
              field:
                  element: hidden
                  value: ""
    ignore:
        - .gitignore
        - .htaccess
        - _config.yml
        - favicon.ico
        - feed.atom
        - Gemfile
        - Gemfile.lock
        - identicon.png
        - README.md
        - robots.txt
        - 404.html
        - index.html
        - /_layouts
        - /_includes
        - /_site
        - /assets
        - /css
        - /js
        - /links
