### Site info:
title: Medicare Blog
tagline: The Official Blog for U.S. Medicare Program. For more information, please visit www.medicare.gov

author: Mohanraj Balasubramanian

baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "medicare-blog.github.io" # the base hostname & protocol for your site

### Personal info and site tools info:

favicon:     "/images/favicon.ico

lsi: false

parmalink: /:categories/:title.html

### Build settings
markdown: rdiscount
highlighter: pygments
paginate: 5

exclude:
    - LICENSE
    - README.md

# Prose settings
prose:
  media: 'assets'
  rooturl: "_posts"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
