### Site info:
title: Medicare Blog
tagline: The Official Blog for U.S. Medicare Program. For more information, please visit www.medicare.gov

author: Mohanraj Balasubramanian

baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "medicare-blog.github.io" # the base hostname & protocol for your site


### Personal info and site tools info:

favicon:     "/images/favicon.ico"

lsi: false

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

parmalink: /:categories/:title.html


### Build settings
markdown: rdiscount
highlighter: pygments
paginate: 5


exclude:
    - LICENSE
    - README.md

# Prose settings
prose:
  media: 'assets'
  rooturl: "_posts"
  siteurl: "https://ecwsproc:W3lcome$$@prod-t.healthcare.gov/"
  relativeLinks: "https://ecwsproc:W3lcome$$@prod-t.healthcare.gov/resources/prose/relativeLinks.jsonp"
  site:
    tags: "https://ecwsproc:W3lcome$$@prod-t.healthcare.gov/api/tags.jsonp"
  metadata:
    _posts:
      - name: "lang"
        field:
          element: "select"
          label: "Select language"
          placeholder: "English"
          options: *languages
          selected: "en"
